yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name="Название")
    slug = models.SlugField(unique=True, max_length=50, verbose_name="Ссылка")
    description = models.TextField(
        max_length=500,
        blank=True,
        verbose_name="Описание"
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Сообщество"
        verbose_name_plural = "Сообщества"


class Post(models.Model):
    text = models.TextField(verbose_name="Текст")
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата публикации"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name="Автор"
    )

    def __str__(self):
        return self.text

    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name="Группа"
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = "Посты"

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    text = forms.CharField(
        widget=forms.Textarea,
        label='Введите текст',
        required=True,
        help_text='Текст поста'
    )

    class Meta:
        model = Post
        fields = ('text', 'group')
        labels = {'group': 'Выберите нужную группу'}
        help_text = {'group': 'Группа поста'}

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import Group, Post, User

NUMBER_POSTS: int = 10


def paginator_func(posts, request):
    paginator = Paginator(posts, NUMBER_POSTS)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


def index(request):
    posts = Post.objects.all()
    page_obj = paginator_func(posts, request)

    context = {
        'page_obj': page_obj,
    }

    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = paginator_func(posts, request)

    context = {
        'group': group,
        'page_obj': page_obj,
    }

    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = paginator_func(posts, request)
    context = {
        'author': author,
        'page_obj': page_obj,
        'posts_count': author.posts.count(),
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post': post,
        'author': post.author,
        'posts_count': post.author.posts.count(),
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form},)
    new_post = form.save(commit=False)
    new_post.author = request.user
    new_post.save()
    return redirect('posts:profile', request.user)


@login_required
def post_edit(request, post_id, template='posts/create_post.html'):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST, instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(instance=post)
    return render(request, template,
                  {'post': post, 'form': form, 'is_edit': True})

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
{% if is_edit %}
  Сохранить запись
{% else %}
  Добавить запись
{% endif %}
{% endblock %}
{% load user_filters %}
{% block content %}
<style>
  textarea {
  width: 100%; /* Ширина поля в процентах */
  height: 175px; /* Высота поля в пикселах */
  }
</style>
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Сохранить запись
          {% else %}
            Добавить запись
          {% endif %}
        </div>
        <div class="card-body">
        {% if is_edit %}
          <form method="post" enctype="multipart/form-data"
          action="{% url 'posts:post_edit' post.pk %}">
        {% else %}
          <form method="post" enctype="multipart/form-data"
          action="{% url 'posts:post_create' %}">
        {% endif %}
          {% csrf_token %}
            {% for field in form %}
            <div class="form-group row my-3 p-3 textarea">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>
              {{ field|addclass:'form-control' }}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help"
                class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
{{ group.title }}
{% endblock %}
{% block content %}
<h1> {{ group.title }} </h1>
<p> {{ group.description }} </p>
{% for post in page_obj %}
<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name|linebreaksbr }}
    </li>
    <li>
      <b>Дата публикации:</b> {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text|linebreaksbr }}</p>
  </article>
  {% if not forloop.last %} <hr> {% endif %}
{% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %} Последние обновления на сайте {% endblock title %}
{% block content %}
<h1> Последние обновления на сайте </h1>
<hr>
{% for post in page_obj %}
<article>
<ul>
  <li>
    <b>Автор:</b>  <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
  </li>
  <li>
    <b>Дата публикации:</b> {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>
<p>{{ post.text }}</p>
{% if post.group %}
<a href="{% url 'posts:group_list' post.group.slug %}" class="btn btn-outline-primary btn-sm">>>>Все записи группы</a>
{% endif %}
</article>
  {% if not forloop.last %} <hr>{% endif %}
{% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock content%}

yatube/templates/posts/post_detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}
    {% block content %}
        <div class="row">
        <aside class="col-12 col-md-3">
          <article class="col-12 col-md-12"
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации:<br>  {{ post.pub_date }}
            </li>
            {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group }}<!-- Название группы -->
              <br><a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              {% endif %}
              </a>
            </li>
            <li class="list-group-item">
              Автор: <span> {{ author.get_full_name }} </span >
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  {{ posts_count }}
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
           {{ post.text|linebreaks }}
          </p>
          {% if user == post.author %}
        <a class="btn btn-outline-primary" href="{% url 'posts:post_edit' post.pk %}">
          Редактировать запись
        </a>
      {% endif %}
    </article>
  </div>
      </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
Профиль пользователя {{ author.get_full_name }}
{% endblock title %}
{% include 'includes/header.html' %}
{% block content %}
  <h1>Все посты пользователя {{ author.get_full_name }} </h1>
  <h3>Всего постов: {{ posts_count }} </h3>
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор: {{ author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d M Y" }}<!-- 31 июля 1854 -->
      </li>
    </ul>
    <p>
      {{ post.text|linebreaksbr }}
    </p>
    <ul>
      <li>
        <a href="{% url 'posts:post_detail' post.pk %}">Подробная информация </a>
      </li>
      <li>
        {% if post.group %}
         <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group }}</a>
        {% endif %}
      </li>
    </ul>
    {% if not forloop.last %}
    <hr>
    {% endif %}
  </article>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}